### ISSUE TITLE
AuthHttpClient.java:45-46: Start decorating our internal...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#172] opened 2018-11-04 16:46 UTC
The puzzle `99-3f73ab5f` from #99 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/ab0d78ec783de53306d63a66dd459598d58dc8c4/src/main/java/com/amihaiemil/docker/AuthHttpClient.java#L45-L46

The puzzle was created by rultor on 23-May-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment] 2018-11-04 16:46
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment] 2018-11-04 16:50
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-11-04 17:02
Job [#172](https://github.com/amihaiemil/docker-java-api/issues/172) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-12-03 15:46
The job [#172](https://github.com/amihaiemil/docker-java-api/issues/172) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/c30ba06b-5c5d-4a03-9490-455d25796525); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by bkuzmic** [comment] 2018-12-06 08:39
@0crat wait for clearing the requirement

**Comment by amihaiemil** [comment] 2018-12-06 08:41
@bkuzmic Can you open a new ticket for clarification? I would like to assign it to @llorllale -- he implemented all this auth stuff, maybe he knows it better than me :)

**Comment by bkuzmic** [comment] 2018-12-06 08:42
@amihaiemil Sure, no problem.

**Comment by 0crat** [comment] 2018-12-06 08:44
> @0crat wait for clearing the requirement ([here](https://github.com/amihaiemil/docker-java-api/issues/172#issuecomment-444792138))

@bkuzmic The impediment for [#172](https://github.com/amihaiemil/docker-java-api/issues/172) was registered successfully by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by amihaiemil** [comment] 2018-12-06 08:44
@bkuzmic I think you already spent some time on it so make a PR and change the puzzle (change the ticket origin and reference your comment here, for the next assignee.

**Comment by 0crat** [comment] 2018-12-06 14:02
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @0pdd[/z](https://www.0crat.com/u/0pdd) (its creator); I won't close the order; please, re-open it and ask @0pdd[/z](https://www.0crat.com/u/0pdd) to close it

**Comment by 0crat** [comment] 2018-12-06 14:04
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by bkuzmic** [comment] 2018-12-18 07:43
@amihaiemil I think we can close this one, right? I've also noticed that for building images and using X-Registry-Config header, there can be multiple key-value pairs for registries, like this:
```
{
  "docker.example.com": {
    "username": "janedoe",
    "password": "hunter2"
  },
  "https://index.docker.io/v1/": {
    "username": "mobydock",
    "password": "conta1n3rize14"
  }
}
```
I will have to create another puzzle to extend recently added RegistyConfigAuth and support multiple registries.

**Comment by amihaiemil** [comment] 2018-12-18 07:47
@bkuzmic Yes, we can close it. 

>I will have to create another puzzle to extend recently added RegistyConfigAuth and support multiple registries.

Just open a ticket directly :)

**Closed by amihaiemil** 2018-12-18 07:47 UTC
Labels: bug, pdd

**Comment by 0crat** [comment] 2018-12-18 08:08
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@eb89e8d3-0095-4fbe-a3fc-12ba67735974, thread: AsyncProc-3
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:amihaiemil/docker-java-api#172] declared for identity constraint of element "verbosity".
```

[0.39.7](https://github.com/zerocracy/farm): CID: [483bfdca-879b-49b4-9aa1-0125c15dd5c4](https://www.0crat.com/footprint/G6LPQQV2P/483bfdca-879b-49b4-9aa1-0125c15dd5c4), Type: "Close job"

**Comment by 0crat** [comment] 2018-12-18 08:15
The job [#172](https://github.com/amihaiemil/docker-java-api/issues/172) is now out of scope

**Comment by 0crat** [comment] 2018-12-18 08:15
Order was finished: +30 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment] 2018-12-18 08:15
Job `gh:amihaiemil/docker-java-api#172` doesn't exist in WBS, can't create order
