### ISSUE TITLE
Combined extends JsonResource

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#138] opened 2018-06-13 10:54 UTC
Let's add this and use it where we need to combine the user's input JsonObject with the API's output JsonOBject (e.g. when creating a Container, or a Swarm etc)

**Comment by 0crat** [comment] 2018-06-13 10:58
The job [#138](https://github.com/amihaiemil/docker-java-api/issues/138) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1641059022); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2018-06-13 10:58
Job `gh:amihaiemil/docker-java-api#138` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment] 2018-06-13 11:00
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment] 2018-06-13 11:00
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment] 2018-06-13 11:00
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment] 2018-06-14 14:44
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (its creator); I won't close the order; please, re-open it and ask @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) to close it

**Closed** 2018-06-14 14:49 UTC
Labels: 0.0.2, bug

**Comment by 0crat** [comment] 2018-06-14 15:05
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@23358be6-5f5f-464a-a807-521a2e91d870, thread: AsyncFlush-3
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:amihaiemil/docker-java-api#138] declared for identity constraint of element "verbosity".
```

[0.22.3](https://github.com/zerocracy/farm): CID: [1651462949](https://www.0crat.com/G6LPQQV2P/1651462949), Type: "Close job", Author: "amihaiemil"

**Comment by 0crat** [comment] 2018-06-14 15:05
Order was finished: +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment] 2018-06-14 15:05
The job [#138](https://github.com/amihaiemil/docker-java-api/issues/138) is now out of scope
